version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    network_mode: "host"
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    network_mode: "host"
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_CREATE_TOPICS: "inputTopic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-2:
    image: wurstmeister/kafka
    network_mode: "host"
    ports:
      - "9093:9093"
    environment:
      KAFKA_PORT: 9093
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_CREATE_TOPICS: "inputTopic:1:1"
      KAFKA_ZOOKEEPER_CONNECT: localhost:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafdrop:
    image: thomsch98/kafdrop
    container_name: kafdrop
    network_mode: "host"
    environment:
      # yes localhost as its a client side app outsite of the docker network on your host
      - ZK_HOSTS=localhost:2181
      - LISTEN=9000
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper